const CONSTANTS = {
  home: 'ana sayfa',
  homePath: '/',
  homeIcon: '/icons/home.svg',
  homeIconBg: '/icons/homeBg.svg',
  add: 'ilan ver',
  addPath: '/ilan-ver',
  addIcon: '/icons/add.svg',
  addIconBg: '/icons/addBg.svg',
  account: 'hesabım',
  accountPath: '/hesabim',
  accountIcon: '/icons/user.svg',
  accountIconBg: '/icons/userBg.svg',
  searchIconPath: '/icons/search.svg',
  ayakkabi: 'ayakkabı makineleri',
  ayakkabiPath: '/1-ayakkabi-makineleri',
  kesim: 'kesim makineleri',
  kesimPath: '/3-kesim-makineleri',
  taban: 'taban makineleri',
  tabanPath: '/2-taban-makineleri',
  kemer: 'kemer makineleri',
  kemerPath: '/4-kemer-makineleri',
}

export default CONSTANTS