const CONSTANTS = {
  home: 'ana sayfa',
  homePath: '/',
  homeIcon: '/icons/home.png',
  homeIconBg: '/icons/homeBg.png',
  add: 'ilan ver',
  addPath: '/ilan-ver',
  addIcon: '/icons/add.png',
  addIconBg: '/icons/addBg.png',
  account: 'hesabım',
  accountPath: '/hesabim',
  accountIcon: '/icons/user.png',
  accountIconBg: '/icons/userBg.png',
  searchIconPath: '/icons/search.png',
  cancelIconPath: '/icons/cancel.png',
  ayakkabi: 'ayakkabı makineleri',
  ayakkabiPath: '/1-ayakkabi-makineleri',
  kesim: 'kesim makineleri',
  kesimPath: '/3-kesim-makineleri',
  taban: 'taban makineleri',
  tabanPath: '/2-taban-makineleri',
  kemer: 'kemer makineleri',
  kemerPath: '/4-kemer-makineleri',
}

export default CONSTANTS